### ISSUE TITLE
Hash functions used?

### ISSUE THREAD

**Issue by Kaiyiccc** [x13a/py-minisign#1]
Cryptography newbie here, hoping to get a better understanding of the hash functions used by py-minisign:

The [IETF RFC8032](https://tools.ietf.org/html/rfc8032) specifies Ed25519 using SHA-512, both as (1) the **hash function to compute the signature**, and as (2) **the "prehash"for large messages in the Ed25519ph specification**.

I looked at py-minisign and only found Blake2

1. Is py-minisign using Blake2 instead of SHA-512 both in (1) and (2)? Or only in (2) prehash stage?

2. What's the considerations behind this? Is it mainly because Blake2 is faster?

Thank you.

**Comment by x13a** [comment]
You have to ask @jedisct1 about design decisions, he is an author of [minisign](https://github.com/jedisct1/minisign). I only ported it.

For `Ed25519` I have used [cryptography](https://github.com/pyca/cryptography) package, `blake2b` is used for prehash and secret key checksum. Full specs are available at the bottom [here](https://jedisct1.github.io/minisign/).

**Comment by jedisct1** [comment]
Minisign was written before the Ed25519ph specification :)

The Ed25519ph specification uses SHA-512 for prehashing because that function is already a requirement to compute a regular Ed25519 signature, so it could be reused.

But any collision-resistant hash function provides the same security guarantees. BLAKE2 is faster and the default hash function in libsodium. Not a lot of applications use Ed25519ph as specified, and most libraries including Ed25519 don't even implement it.

**Comment by jedisct1** [comment]
For the signature computation itself, the internal function remains SHA-512. This is the standard Ed25519 construction.

**Comment by Kaiyiccc** [comment]
Thanks for the prompt response!

@jedisct1 If it's possible to confirm my understanding: 

The only difference between the **IETF "Ed25519ph"** specification, and **minisign's "Ed25519 with prehash"**, is in the choice of the prehash function?

**i.e. If I fork py-minisign, change the prehash function from BLAKE2 to SHA-512, it would be exactly the same as IETF's Ed25519ph?**

---

I'm only confused by the dom2(f,c) expression, where f: prehashflag (boolean) and c: context

![image](https://user-images.githubusercontent.com/66088388/112382456-3ffcac80-8cc2-11eb-9f3e-86bd45e8142b.png)
[image source](https://www.cryptologie.net/article/497/eddsa-ed25519-ed25519-ietf-ed25519ph-ed25519ctx-hasheddsa-pureeddsa-wtf/)

> For Ed25519, dom2(f,c) is the empty string.  The phflag value is irrelevant.  The context (if present at all) MUST be empty...
>...
> For Ed25519ph, phflag=1...

Does it mean when I do a prehash, I also need to prepend the phflag=1 somewhere? Or is the phflag=1 just a conditional statement, not an input to the algorithm?

Thank you in advance.

**Comment by jedisct1** [comment]
`Ed25519ph(m)` could have been defined as `Ed25519(SHA-512(m))`. Which would have made all existing implementations immediately compatible, and avoid code duplication.

Unfortunately, this is not case. A prefix is added in the internal function. Just linking an answer I gave a while back about this: https://crypto.stackexchange.com/questions/72035/difference-between-pure-eddsa-ed25519-and-hasheddsa-ed25519ph

**Comment by Kaiyiccc** [comment]
Thank you for the clarification!

For my purpose: finding a Python ed25519ph implementation,

I dug around and found [py-nacl 1.3.0](https://pynacl.readthedocs.io/en/stable/changelog/#id2) added low-level bindings to the [libsodium ed25519ph implementation](https://libsodium.gitbook.io/doc/public-key_cryptography/public-key_signatures#multi-part-messages), but there isn't an API yet.
